import time
import requests
from typing import Any, Dict


# ============================================================
# OLLAMA CONFIGURATION
# ============================================================

OLLAMA_URL = "http://127.0.0.1:11434/api/chat"
OLLAMA_MODEL = "qwen3:1.7b"

# Local LLM can take several seconds on RTX 2050 / CPU.
OLLAMA_TIMEOUT = 180

# Retry only temporary failures.
MAX_RETRIES = 3


# ============================================================
# AI EXPLANATION SERVICE
# ============================================================

def generate_plan_explanation(
    optimization_result: Dict[str, Any],
) -> str:
    """
    Generate an operator-friendly explanation of an
    already-validated OR-Tools optimization result.

    IMPORTANT ARCHITECTURE:
    - OR-Tools generates the schedule.
    - OR-Tools constraints remain authoritative.
    - Qwen3 ONLY explains the supplied result.
    - Qwen3 does NOT create or modify schedules.
    - No cloud AI API is used.
    """

    prompt = f"""
You are the decision-support explanation assistant for RailAnukriti.

IMPORTANT:
The following plan has ALREADY been generated by an OR-Tools
constraint optimizer.

Your ONLY task is to explain the supplied optimization result.

You MUST NOT:
- create a schedule
- modify a schedule
- validate a schedule
- recommend a different schedule
- invent railway rules
- invent safety guarantees
- invent train information
- invent maintenance requirements
- invent resource utilization claims
- invent operational benefits
- invent performance improvements

Use ONLY facts explicitly present in the supplied optimization result.

If a requested fact is not present, write:
"Not specified in the optimization result."

OPTIMIZATION RESULT:
{optimization_result}

Write a concise operator explanation using EXACTLY these sections:

1. Plan Summary
2. Why This Plan Was Selected
3. High-Priority Maintenance
4. Train Protection
5. Efficiency Improvement
6. Operator Considerations

Rules:

For Plan Summary:
Only summarize facts present in the optimization result.

For Why This Plan Was Selected:
Only explain the optimization objectives or results explicitly present
in the optimization result.

For High-Priority Maintenance:
Only mention tasks and priority information explicitly present.

For Train Protection:
Only report the provided train-conflict information and protected trains.

For Efficiency Improvement:
ONLY mention numerical improvements explicitly present in the result.
Do not calculate new improvements.

For Operator Considerations:
State that this is a synthetic prototype simulation and not an official
railway operating recommendation.

Do not add any other sections.
"""


    payload = {
        "model": OLLAMA_MODEL,
        "messages": [
            {
                "role": "user",
                "content": prompt,
            }
        ],
        "stream": False,
        "think": False,
        "options": {
            "temperature": 0.1,
            "num_predict": 300,
        },
    }


    # ========================================================
    # OLLAMA REQUEST WITH RETRIES
    # ========================================================

    for attempt in range(1, MAX_RETRIES + 1):

        try:
            print(
                f"[AI] Attempt {attempt}/{MAX_RETRIES} "
                f"→ Ollama {OLLAMA_MODEL}"
            )

            response = requests.post(
                OLLAMA_URL,
                json=payload,
                timeout=OLLAMA_TIMEOUT,
            )

            print(
                f"[AI] Ollama HTTP status: "
                f"{response.status_code}"
            )

            # ------------------------------------------------
            # Temporary Ollama/server failure
            # ------------------------------------------------

            if response.status_code >= 500:

                print(
                    "[AI] Ollama server error:",
                    response.text[:500],
                )

                if attempt < MAX_RETRIES:
                    print("[AI] Retrying...")
                    time.sleep(2)
                    continue

                response.raise_for_status()


            # ------------------------------------------------
            # Other HTTP errors
            # ------------------------------------------------

            response.raise_for_status()


            # ------------------------------------------------
            # Parse JSON
            # ------------------------------------------------

            data = response.json()

            print("[AI] Ollama JSON response received.")


            # ------------------------------------------------
            # Extract assistant content safely
            # ------------------------------------------------

            message = data.get("message", {})

            content = message.get("content", "")


            if not content:
                print(
                    "[AI] Ollama returned no assistant content."
                )

                raise RuntimeError(
                    "Ollama returned an empty AI explanation."
                )


            print("[AI] AI explanation generated successfully.")

            return content.strip()


        # ====================================================
        # TIMEOUT
        # ====================================================

        except requests.exceptions.Timeout as exc:

            print(
                f"[AI] Ollama timeout on attempt "
                f"{attempt}/{MAX_RETRIES}:",
                repr(exc),
            )

            if attempt < MAX_RETRIES:
                print("[AI] Retrying after timeout...")
                time.sleep(2)
                continue

            raise RuntimeError(
                "Ollama timed out while generating the AI explanation."
            ) from exc


        # ====================================================
        # CONNECTION / REQUEST ERROR
        # ====================================================

        except requests.exceptions.ConnectionError as exc:

            print(
                f"[AI] Ollama connection error on attempt "
                f"{attempt}/{MAX_RETRIES}:",
                repr(exc),
            )

            if attempt < MAX_RETRIES:
                print("[AI] Retrying connection...")
                time.sleep(2)
                continue

            raise RuntimeError(
                f"Unable to connect to local Ollama: {exc}"
            ) from exc


        # ====================================================
        # OTHER REQUEST ERRORS
        # ====================================================

        except requests.exceptions.RequestException as exc:

            print(
                "[AI] Ollama request failed:",
                repr(exc),
            )

            raise RuntimeError(
                f"Ollama request failed: {exc}"
            ) from exc


        # ====================================================
        # INVALID RESPONSE
        # ====================================================

        except (KeyError, TypeError, ValueError) as exc:

            print(
                "[AI] Invalid Ollama response:",
                repr(exc),
            )

            raise RuntimeError(
                f"Unexpected Ollama response: {exc}"
            ) from exc


    raise RuntimeError(
        "AI explanation could not be generated."
    )